config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include('project.urls')),
    path('', include('home.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import landing_page, GetTest


urlpatterns = [
    path('landing/', landing_page, name='landing_page'),
    path('test/', GetTest.as_view(), name='test')
]

project/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView

app_name = 'project'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

home/models.py
from django.db import models

# Create your models here.

project/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomerUser(AbstractUser):
    image = models.ImageField(upload_to='user_image/', blank=True, null=True, default='default_img/download.png')

    class Meta:
        db_table = 'customuser'

    def __str__(self):
        return self.username

project/forms.py
from django import forms
from .models import CustomerUser


class CustomUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomerUser
        fields = ('username', 'email', 'first_name', 'last_name', 'image', 'password')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


def landing_page(request):
    return render(request, 'landing_page.html')


class GetTest(LoginRequiredMixin, View):
    def get(self, request):
        if request.user.is_authenticated:
            return render(request, 'get_test.html')
        else:
            return redirect('project:login')

project/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import CustomerUser
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CustomUserForm


class RegisterView(View):
    def get(self, request):
        create_form = CustomUserForm()
        context = {
            'form': create_form
        }
        return render(request, 'register.html', context=context)

    def post(self, request):
        creat_form = CustomUserForm(data=request.POST, files=request.FILES)
        if creat_form.is_valid():
            creat_form.save()
            return redirect('project:login')
        else:
            context = {
                'form': creat_form
            }
            return render(request, 'register.html', context=context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        context = {
            'form': login_form
        }
        return render(request, 'login.html', context=context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect('/landing')
        else:
            context = {
                'form': login_form
            }
            return render(request, 'login.html', context=context)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('landing_page')

project/templates/login.html
{% extends "master.html" %}

{% block title %}
    login page
{% endblock %}

{% block content %}
<h1>Login Page</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Submit</button>

</form>

{% endblock %}

project/templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

project/templates/register.html
{% extends "master.html" %}

{% block title %}
    register page
{% endblock %}

{% block content %}
<h1>Login Page</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Submit</button>

</form>

{% endblock %}

templates/get_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>hello django</h1>
</body>
</html>

templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
</head>
<body>
<h1>Home page</h1>
<a href="{% url 'project:register' %}">Register</a> /
<a href="{% url 'test' %}">Test</a> /
{% if request.user.is_authenticated %}
    <a href="{% url 'project:logout' %}">Logout</a>
{% else %}
    <a href="{% url 'project:login' %}">Login</a>
{% endif %}
</body>
</html>